#!/usr/bin/perl
use strict;
use warnings;
use Filesys::DiskSpace;
my $dir = "/home";
my ($fs_type, $fs_desc, $used, $avail, $fused, $favail) = df $dir;
my $df_free = (($avail) / ($avail+$used)) * 100.0;
my $out = sprintf("Disk space on $dir: %0.2fn",$df_free);
print $out;