#!/usr/bin/expect

# logging into ssh

set index [lindex $argv 0];

spawn bash ssh_command.sh $index
expect {
    "yes/no" {
        send "yes\r"
        expect "*?assword" {
            send "password\r"
        }
    } 
    
    "*?assword" {
        send "password\r"
    }

    "127.0.0.1" {
        send "sudo ./ssh.exp $index"
    }
    
    "*?onnection refused" {
        spawn "echo 'WHAT THE\n\n'"
        send "sudo ./ssh.exp $index"
    }
}